language: python
python:
  - "2.6"
  - "2.7"
services:
  - redis-server
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install coverage python-coveralls --use-mirrors
script:
  - coverage erase
  - coverage run --source fakeredis.py test_fakeredis.py
notifications:
  email:
    - js@jamesls.com
after_success: coveralls
